services:
  - type: web
    name: qadeer-ai
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.16.0
      - key: BOT_NAME
        value: QADEER AI
